### ISSUE TITLE
Service metrics in json format

### ISSUE THREAD

**Issue by rafaelldi** [dotnet/tye#1108]
Hello!
Endpoint `/api/v1/metrics/{{service}}/` produces response like this:
```
Microsoft.AspNetCore.Hosting/failed-requests{instance="api_70f4d32f-5"} 0
System.Runtime/gen-1-gc-count{instance="api_70f4d32f-5"} 0
Microsoft.AspNetCore.Hosting/current-requests{instance="api_70f4d32f-5"} 0
Microsoft.AspNetCore.Hosting/total-requests{instance="api_70f4d32f-5"} 0
Microsoft.AspNetCore.Hosting/requests-per-second{instance="api_70f4d32f-5"} 0
```
I found this format difficult to parse. Would you mind making it more json-way, please?

**Comment by rafaelldi** [comment]
@philliphoff @pratiksanglikar 
Could you please review my question? I can open a pull request for this change. I think it would also be handy for vs code extension if you plan to add a metrics dashboard to it.

**Comment by philliphoff** [comment]
@rafaelldi I had to take a little time to dig into the code and determine why it is using this particular format and it turned out to be Kubernetes own metrics logging format.  I imagine it was done this way to enable integration with existing Kubernetes metrics monitoring tools.

That said, I don't see any reason why Tye couldn't support both, if JSON was a simpler format to consume.  In fact, there's a bug in the `/metrics/<service>` endpoint where it claims to return JSON even though it clearly is not.  (The `/metrics` endpoint doesn't return any `content-type`, though it arguably should.)

Here's what I suggest, if you're willing to submit a PR:

 - Either by default or when text is specifically requested, for both `/metrics` and `/metrics/<service>` endpoints, return the current Kubernetes text format with the appropriate text `content-type` header in the response.
 - When JSON is specifically requested, for both endpoints, return a JSON format with the appropriate JSON `content-type` header in the response.

As for the JSON format, perhaps something along these lines?

```json
[
  {
    "name": "Microsoft.AspNetCore.Hosting/failed-requests",
    "metadata": {
      "instance": "api_70f4d32f-5"
    },
    "value": 0
  }
]
```

**Comment by rafaelldi** [comment]
Thank you for your time. I'll try to do it as you've advised soon.

**Comment by davidfowl** [comment]
It's currently the Prometheus format I believe

**Comment by rafaelldi** [comment]
Yes, you are right, it's a Prometheus format. In my PR #1130, I've replaced the `application/json` content-type header with `text/plain`, as it said in the Prometheus [documentation](https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format).

Also, I've added json format because I think that it's more convenient to use it in different tooling.

**Comment by philliphoff** [comment]
Closing per #1130.
