### ISSUE TITLE
Version NetCore 3.1    ???    -->   net5  or net6 preview?? please update

### ISSUE THREAD

**Issue by WuMianRen** [dotnet/tye#1120]
### Some details

**How many services are in your application? (including things like databases, redis):**

- [ ] 1-2
- [ ] 3-5
- [ ] 6-10
- [x] 10+

**What did you use tye for?**

- [x] Local development
- [ ] Deployment

**How is your code organized?**

- [ ] One service per repo
- [x] Many services in one big repo
- [ ] Other (please explain)

**Comment by philliphoff** [comment]
@WuMianRen Are you requesting that the Tye CLI/host itself move to .NET 5/6, or something else?  As .NET Core 3.1 is in LTS for quite some time, and overlaps .NET 6 which will also be a LTS release, I expect that we'd move to .NET 6, but not until it GAs later this year.  That said, I'm not sure yet how we'll manage, say, `arm64` vs. `amd64` flavors of .NET; it's something that needs some investigation.

**Comment by paulyuk** [comment]
@philliphoff could Tye at least run with .NET 5?  that is current recommended even for MacOS.  When I run with just .NET 5 I see this:
---
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.9 at [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=osx.11.0-x64

**Comment by philliphoff** [comment]
@paulyuk Where's the recommendation for using .NET 5 on Mac?  (Not questioning, but curious given it's not a LTS release.) I don't believe that .NET Core 3.1 apps can "just run" on .NET 5 via configuration, as one could do with .NET Framework.  So we'd either have to move Tye to .NET 5, or multi-target and multi-release Tye for both Core 3.1 and 5.  Then the question would be, if 5, why not 6 (given we're already at Preview 7) and that *is* going to be a LTS release?  And then, if 6, is that `arm64` (M1-compatible) 6 or `amd64` 6?  I have a [branch](https://github.com/dotnet/tye/tree/philliphoff-arm64) that is a PoC for `arm64` 6 support so that I can be productive on my M1 Mac, but it would require much more testing to consider it "ready for release", and then the question is still how to best to support the various flavors of 6.

**Comment by WuMianRen** [comment]
@philliphoff 
ok。thakn you
First, I learned about tye from dapr
Then start the research on it
But as more programs are developed and deployed
My native environment began to become complex
SDKs of multiple dotnets appear (e.g. 2.1 2.2 3.1 5.0 6.0 preview 1-6)
Sometimes I don't want so many SDKs on the server
So I put forward this issue, and think that type follows the life cycle of NETCORE, at least in terms of version
But you have replied, and I will update it to the LTS of net6
So this issue is meaningless
Thank you again
