### ISSUE TITLE
Run Tye with Dapr

### ISSUE THREAD

**Issue by SiddyHub** [dotnet/tye#1154]
I have a query regarding the usage of Tye with Dapr. Can both be used to together, because to run Tye, first we have to run Dapr runtime in the background for service discovery to work. So how can we debug application with Tye, if we use it with Dapr?
Any thoughts or suggestions on the same, would be great.

**Comment by xavidram** [comment]
When working with Dapr and Tye. When your run your applications using `tye run --dashboard` you can see the sidecars that are also spun up by Tye for you. Take a look at this guide [here](https://github.com/dotnet/tye/blob/main/docs/recipes/dapr.md).

Simply invoke your sidecars using the DaprClient via either the DaprInvokeMethodAsync or by creating a DaprClient based on the appId of the microservice you need to access.

For Example let's say you have two microservices: `app1` and `app2`. In order to invoke a call from app1 to app2 you can do something similar.

```
var client = DaprClient.InvokeHttpClient("app1");
var requestData = await client.GetAsync('endpoint/path');
```

If you spin up the `Zipkin` extension with tye, and make an invocation request to one of your microservices using the Service-to-service methodology. You will see Zipkin will log the route call. When inspecting the route call you will notice it will use the invoke method endpoint to access your Dapr sidecar.

By using the `Microsoft.Tye.Extensions.Configuration` package for [Service Discovery](https://github.com/dotnet/tye/blob/main/docs/reference/service_discovery.md). Tye will help you find the ports to your Sidecars based on the AppId you gave your service in the Tye.yaml configuration file.

The documentation is pretty extensive and well documented.
