### ISSUE TITLE
Figure out how to make ingress work for deployment

### ISSUE THREAD

**Issue by davidfowl** [dotnet/tye#183]
Today ingress is modeled as a set of routing rules (either path or hostname) that map to a particular service. We should figure out how this applies to deployments.

- Do we deploy a particular ingress controller as well as setup ingress rules in k8s?
- Do we pick a specific ingress controller (nginx?)? Should we mirror that locally?

**Comment by rynowak** [comment]
My plan was that we'd pick nginx-ingress to document/support. It's the most well-known ingress controller, and it's easy to find docs and samples. It's also maintained by Kubernetes, so it's not going away on a whim.

As far as deploying - I think we need a couple of things:

- Deploy (from a pre-canned k8s yaml that we link to) as part of interactive mode
- Check (verify that it's already deployed with some default name) as part of non-interactive mode
- Bind to existing ingress (customize the name in tye.yaml) 

This is pretty similar to the flow that we do today for creating secrets. I feel little bit more comfortable giving people a way to deploy nginx for ingress rather than a databases because there's a million tutorials for this already, and a proxy has fewer moving parts.

As a note here, the only thing that's really particular to *which* ingress you're using (I think) is the ingress class annotation. So in theory we could make our services/deployments work with any ingress, assuming you've already deployed it, and can tell us where to find it.

**Comment by RichiCoder1** [comment]
Possibly a separate issue than this, but one thing that I've seen a lot of for users of alternative gateways like [Ambassador](https://www.getambassador.io/) or [Gloo](https://gloo.solo.io/) is they ultimately use their own custom resources to define routes. I think an MVP that supports `Ingress` resources with a default controller at first would be great, but it'd be nice further down the line to somehow allow or account for other routing models.

**Comment by rynowak** [comment]
> An empty ingress without paths defined directs traffic to a default backend as defined by the controller, should we support this scenario

One of the reasons why I went the way I did with this (`ingress-nginx`) is that `IngressController` is becoming a [standard resource](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/) in k8s as of 1.18.X. It will be a while before that's available broadly, so we have to think about what the support would be without standard behaviors to rely on - or even a standard way to *know what controller you are using*.

As an example, I had to build-in knowledge of specific labels that `ingress-nginx` uses to detect whether or not its present - which includes different behavior in minikube. There's no universal way do this across controllers today and there won't be for some time.

---

I think we want to get something out there that does something basic, and let the spark more conversation about what people want. I'm about to merge an experience that let you deploy `ingress-nginx` with a generic configuration.

After we get this out there, I'm interested in feedback about:

- Is it useful for us to deploy the ingress controller for you?
- Do you like a simpler *recommended* experience? (or is talking to k8s directly better)
- Does us providing a basic convention-over-configuration setup conflict with giving you control? (we don't give you control yet)

We don't have support today for saying "apply this manifest along with my services please...", but it's a feature I think we'll need to allow you to punch holes in some of the things we're planning.

We could end up in a few different places:

- We unify around a single controller and style of routing as the *golden path*. Everything else is possible but requires work, hopefully less work than it does with tye 😉 
- We end up creating *plugins* for each mainstream ingress controller, with community ownership/support. Similar to what [Dapr are doing](https://github.com/dapr/components-contrib). We would provide the CI and repo, and responsibility for shipping the code. Community members take responsibility for support and maintenance.

**Comment by rynowak** [comment]
This is done for 0.2 - see https://github.com/dotnet/tye/blob/master/docs/recipes/ingress.md
