### ISSUE TITLE
How can I inject dapr.io/config: "tracing" using tye?

### ISSUE THREAD

**Issue by thangchung** [dotnet/tye#296]
Currently, I use `tye` to deploy my application to AKS. Everything is fine now. But with Dapr in-place we can do the tracing out of the box. See at https://github.com/dapr/docs

So I have a quick question that how can we inject `dapr.io/config: "tracing"` into the deployment to enable the tracing with Open Telemetry using `tye`?

**Comment by davidfowl** [comment]
Are you talking about adding annotations for deployment using tye?

**Comment by thangchung** [comment]
Yes, it is. Just adding more like below

```yaml
annotations:
	...
    dapr.io/config: "tracing"
    dapr.io/log-level: "debug"
```

**Comment by davidfowl** [comment]
cc @rynowak

**Comment by rynowak** [comment]
@thangchung - thanks for [blogging us](https://dev.to/thangchung/debugging-dapr-application-using-tye-tool-1djb), I enjoyed the read, and I'm glad you find our project interesting. 

---

We haven't done anything to enable this yet. 

Some ideas:

- We will eventually add some features to customize the k8s manifests annotations and labels, but this doesn't seem like a great case for that because....
- We can add per-extension settings that don't necessary map 1:1 to k8s, or have a different meaning in local development

Example:

```yaml
extensions:
- name: dapr
  config: myconfig
  log-level: debug
```

This would map to the annotations you defined above when deployed, and could map to `config myconfig -log-level=debug` when running locally. 

This seems like it should *just work* would all you to have access to all of dapr's config settings in local dev. 

If you're interested in sending a PR - all the changes would go into [DaprExtension](https://github.com/dotnet/tye/blob/master/src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs). Otherwise, I can add this sometime in the next few days.

**Comment by rynowak** [comment]
Keeping open because I need to fix something with the local dev part of this. Deployment support is merged. Thanks @thangchung 👍
