### ISSUE TITLE
Figure out how to get rid of `AddTyeSecrets`

### ISSUE THREAD

**Issue by rynowak** [dotnet/tye#313]
We should make this go away as a required piece of code, but keep the functionality somehow.

Ideas:

- [ ] Don't use files on disk (has drawbacks: less secure and can't update in place)
- [ ] Build this into ASP.NET Core somehow
- [ ] Replace CreateDefaultBuilder with our own thing
- [ ] Inject a hosting startup in production
- [ ] Inject a hosting startup and dependencies during publishing

**Comment by davidfowl** [comment]
>  Don't use files on disk (has drawbacks: less secure and can't update in place)

I'm not sure updating in place applies to connection strings specifically since they are usually configured at startup in singletons anyways.

Less secure, sure but to be pedantic env variables are stored in virtual file https://stackoverflow.com/questions/532155/linux-where-are-environment-variables-stored 😄

**Comment by davidfowl** [comment]
It also brings consistency between development and production. Which is a huge benefit...
