### ISSUE TITLE
Optional Services

### ISSUE THREAD

**Issue by OneCyrus** [dotnet/tye#501]
We have a microservice architecture with about 10 microservices. Tye is great to get everything up and running on the same box. We are also running all those microservices as dev instances centrally. most of the time when a dev is creating a new feature or fix a bug, he usually makes changes only in about 2-3 services and doesn‘t need all other services actively running on his box. 
to help this scenario it would be awesome to declare some services as optional. this services will set environment variables which point to centrally running http endpoints without starting them locally. the tye frontend now allows this optional services to enable for debugging. this feature will now startup a local instance of this microservice and changes the env variable to this local endpoint.

this would help a lot to keep the resource usage down but still keep it very flexible when the service is needed to make some changes locally.

**Comment by davidfowl** [comment]
Related to https://github.com/dotnet/tye/issues/493

**Comment by jkotalik** [comment]
Today, there are ways to make this work, however they are a bit restrictive. I think there are some nice improvements we can make to smooth the experience out.

The general problem we are trying to solve is how to run or deploy a subset of services specified in a `tye.yaml`. There are are few ways people can go about it, and potentially tye supports all of these options.

### Multiple tye.yaml files

Today, instead of having a single tye.yaml file, you could split your app into multiple tye.yaml files. You could have a top level tye.yaml file, which references all other tye.yaml files in your application. That way, you could run the entire application through the top level tye.yaml, while also having the granularity to run single services.

```yaml
name: myapp
services:
- name: service1
  include: service1/tye.yaml
- name: service2
  include: service2/tye.yaml
```

This approach can work, but has restrictions:
- Not incredibly flexible (hard to specify a set of services easily)
- Can cause dependency issues if you just want to run a subset of services (ex if you have 3 services and you just want to run two, it's a bit complicated to do that.

### Multiple Environments 

We want to add support for multiple environments, where you can specify different tye.yaml files based on the environment you are using (ex local, test deployment, production, etc). This could also be used to specify what services you want to run.

### Tags

As suggested by #493, tags could be a useful way to filter down services that are run. I think an idea like this could be a useful way to filter down to subsets. We need to think a bit about how this applies to tags in Kubernetes deployments as well.

**Comment by OneCyrus** [comment]
templates and presets would be very nice too. but my main point is how could we enable starting up additional services or bypass them on demand? when we need to debug an additional service on the local box it would be cool to bring just this instance up and running without restarting tye (and with it restarting all services which were already running)

i‘m very inspired by the AKS dev spaces concept here. (https://docs.microsoft.com/en-us/azure/dev-spaces/about) but it would be cool to have something similiar locally on the box without actually using containers or k8s cluster.

**Comment by jkotalik** [comment]
Closing as dup of #493
