### ISSUE TITLE
Add support for RabbitMQ as a backend service

### ISSUE THREAD

**Issue by NileshGule** [dotnet/tye#504]
### What should we add or change to make your life better?
Similar to Redis cache support add capability to inject **RabbitMQ** backend service to an application.

### Why is this important to you?
Adding messaging infrastructure to distributed application is a common requirement for building microservices based application. RabbitMQ is one of the popular messaging framework. Having support for messaging using RabbitMQ will be good for migrating existing projects using Tye.

**Comment by rynowak** [comment]
So, something that might help ... Tye doesn't have **any** built-in features for Redis. We happen to use it in a lot of examples, because it's easy to run in a container.

Tye really supports using whatever you want, as long as you know how to describe it. There's an example in our tests using RabbitMQ here: https://github.com/dotnet/tye/blob/master/test/E2ETest/testassets/projects/multi-project/tye.yaml#L16

**Comment by NileshGule** [comment]
> So, something that might help ... Tye doesn't have **any** built-in features for Redis. We happen to use it in a lot of examples, because it's easy to run in a container.
> 
> Tye really supports using whatever you want, as long as you know how to describe it. There's an example in our tests using RabbitMQ here: https://github.com/dotnet/tye/blob/master/test/E2ETest/testassets/projects/multi-project/tye.yaml#L16

Thanks @rynowak for the suggestion. I'll give it a try on one of my project which uses .Net Core for interacting with RabbitMQ. 
https://github.com/nileshgule/pd-tech-fest-2019

**Comment by glennc** [comment]
I don't think there's anything more here for us to do, assuming RabbitMQ works well for you. Create more issues if you have more ideas for better integration or anything as you try it out.
