### ISSUE TITLE
Start all services on specific ports on "tye run"

### ISSUE THREAD

**Issue by pattisapu01** [dotnet/tye#678]
I know "tye" assigns random ports when starting services. But, How do I force "tye" to start listening on specific ports when I "tye run"? I do have different profiles in "LaunchSettings.json". Does tye read "LaunchSettings" file to get the port?

**Comment by tebeco** [comment]
What's your current scenario where you think it would help ?

The launch profile is used from either the `IDE` or `dotnet run --launch-profile XXXX`, it's not intended to be used by tye, you have some of these info inside `tye.yaml`
I wonder if it's not already possible TBH

Though, one of the idea of tye is to be sure everything runs every time you `tye run`
If you attempt to pre-set manually port from a file, the chances are high that it won't run some times (port already in use because it's `static`).
That's why it "look like" random number for port, in fact it's looking for "any free port number"

You can rely on "service discovery" to get the proper endpoint binding/uri
Either 
* by using the `Configuration.GetServiceUri` API from any dotnet application ran BY `tye`
* by using the `tye` REST API that will just like it to you with the associated bindings (litterally any techno that can run `GET` request to the dashboard)

https://github.com/dotnet/tye/blob/master/docs/reference/service_discovery.md

**Comment by pattisapu01** [comment]
We already have a bunch of services that are not integrated with "tye". Some are pure front end apps in Angular (genertaed via Angular CLI, no "csproj" involved) and some are back-end services. The back-end services are the first candidates for "tye" integration. The port numbers when running locally are already hard coded in the "angular" font-end apps (there are multiple front-end apps). Since "Angular" apps are served using "ng serve" and cannot be integrated with "tye", (yet), I am preparing a "script" file that would start the angular app via npm and all the backends via "tye". I don't want to change to dynamic port scenario as I have to modify the angular apps also every time I do "tye run".

**Comment by tebeco** [comment]
I could not have guessed all of that from the original description I suppose.
Is pre-hitting a REST endpoint possible for you as a workaround ?

![image](https://user-images.githubusercontent.com/2266487/94374163-aab19e80-010a-11eb-8e9e-17024880ab90.png)

**Comment by tebeco** [comment]
That being said, in the docs (the same page as `Service Discovery`), it explains what are `binding` and how it can be done so I tried :
Is that what you want ?

![image](https://user-images.githubusercontent.com/2266487/94374497-e9485880-010c-11eb-917d-a9c476d3ec0e.png)

**Comment by tebeco** [comment]
pattisapu01

**Comment by pattisapu01** [comment]
Excellent! That is exactly what I needed.. Should have paid close attention to the schema.. Thx @tebeco !

**Comment by pattisapu01** [comment]
Solved...
